-- Tabla de usuarios del sistema
CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único
  nombre VARCHAR(100),                                    -- Nombre completo
  correo VARCHAR(100),                                    -- Correo electrónico
  rol VARCHAR(50),                                        -- Rol del usuario (admin, editor, etc.)
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP,                               -- Fecha de creación del usuario
  password_hash VARCHAR(255)                              -- Contraseña encriptada
);

-- Tabla de tipo de cambio oficial por fecha
CREATE TABLE tipo_cambio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE UNIQUE,                                      -- Fecha del tipo de cambio
  valor DECIMAL(10,4),                                    -- Valor del dólar en esa fecha
  fuente VARCHAR(100),                                    -- Fuente del dato (ej: Banco Central)
  usuario_registro_id BIGINT REFERENCES usuario(id),      -- Usuario que registró el dato
  fecha_registro TIMESTAMP                                -- Fecha de registro
);

-- Tabla de parámetros comerciales vigentes (tipo de cambio y utilidad)
CREATE TABLE parametros_comerciales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cambio_usado DECIMAL(10,4) CHECK (tipo_cambio_usado > 0),   -- Tipo de cambio positivo
  porcentaje_utilidad DECIMAL(5,2) CHECK (porcentaje_utilidad BETWEEN 0 AND 100), -- Margen válido
  fecha_vigencia DATE NOT NULL,                                    -- Fecha desde la cual aplica
  usuario_editor_id BIGINT REFERENCES usuario(id),                 -- Usuario que modificó el parámetro
  fecha_actualizacion TIMESTAMP DEFAULT NOW()                      -- Fecha de modificación
);

-- Tabla de auditoría de parámetros comerciales
CREATE TABLE auditoria_parametros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único
  parametro VARCHAR(100) NOT NULL,                        -- Nombre del parámetro
  valor_anterior VARCHAR(100),                            -- Valor anterior
  valor_nuevo VARCHAR(100),                               -- Valor nuevo
  usuario_id BIGINT REFERENCES usuario(id),               -- Usuario que realizó el cambio
  fecha TIMESTAMP DEFAULT NOW()                           -- Fecha y hora del cambio
);

-- Tabla de clientes (barcos y operadores)
CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_barco VARCHAR(100) UNIQUE,                       -- Nombre del barco
  imo_numero VARCHAR(20),                                 -- Número IMO
  empresa_operadora VARCHAR(100),                         -- Empresa que opera el barco
  correo_contacto VARCHAR(100),                           -- Correo de contacto
  puerto_base VARCHAR(100),                               -- Puerto base del barco
  pais_origen VARCHAR(50),                                -- País de origen
  tipo_cliente VARCHAR(50),                               -- Tipo de cliente
  capitán VARCHAR(100),                                   -- Nombre del capitán
  cocinero_jefe VARCHAR(100),                             -- Nombre del cocinero jefe
  observaciones TEXT,                                     -- Comentarios adicionales
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP                                -- Fecha de creación del cliente
);

-- Tabla de cotizaciones solicitadas por clientes
CREATE TABLE cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES cliente(id),               -- Cliente que solicita la cotización
  fecha_solicitud DATE,                                   -- Fecha de solicitud
  puerto_destino VARCHAR(100),                            -- Puerto de entrega
  archivo_origen VARCHAR(100),                            -- Nombre del archivo importado
  observaciones TEXT,                                     -- Comentarios adicionales
  usuario_importador_id BIGINT REFERENCES usuario(id),    -- Usuario que importó la cotización
  fecha_importacion TIMESTAMP                             -- Fecha de importación
);

-- Tabla de familias de productos
CREATE TABLE familia_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) UNIQUE,                             -- Nombre de la familia
  descripcion TEXT                                        -- Descripción de la familia
);

-- Tabla de productos disponibles
CREATE TABLE producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  familia_id BIGINT REFERENCES familia_producto(id),      -- Familia a la que pertenece
  descripcion_en TEXT,                                    -- Descripción en inglés
  descripcion_es TEXT,                                    -- Descripción en español
  unidad_medida VARCHAR(20),                              -- Unidad de medida
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos
  fecha_actualizacion TIMESTAMP,                          -- Fecha de última modificación
  usuario_editor_id BIGINT REFERENCES usuario(id)         -- Usuario que editó el producto
);

-- Tabla de ítems dentro de una cotización
CREATE TABLE item_cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización a la que pertenece
  producto_id BIGINT REFERENCES producto(id),             -- Producto vinculado
  descripcion TEXT,                                       -- Descripción libre del ítem
  unidad_medida VARCHAR(20),                              -- Unidad de medida
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos
  tipo_cambio_usado DECIMAL(10,4),                        -- Tipo de cambio aplicado
  precio_costo_neto DECIMAL(12,2),                        -- Precio de costo en USD
  porcentaje_utilidad DECIMAL(5,2),                       -- Margen aplicado
  precio_venta_neto DECIMAL(12,2),                        -- Precio final en USD
  cantidad INT,                                           -- Cantidad solicitada
  total_neto DECIMAL(12,2),                               -- Total neto del ítem
  comentarios TEXT                                        -- Comentarios adicionales
);

-- Tabla de auditoría de importaciones masivas
CREATE TABLE log_importacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización importada
  usuario_id BIGINT REFERENCES usuario(id),               -- Usuario que realizó la importación
  fecha TIMESTAMP,                                        -- Fecha del proceso
  total_items INT,                                        -- Total de ítems procesados
  items_vinculados INT,                                   -- Ítems vinculados correctamente
  items_no_encontrados INT,                               -- Ítems no encontrados en catálogo
  errores_detectados TEXT,                                -- Errores técnicos o de formato
  resumen TEXT                                            -- Resumen general del proceso
);

-- MODELO UNIFICADO CON ALBERTO XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

------------------------------------------------------------
-- BLOQUE A — TABLAS DEL SISTEMA ( MODELO DITTO)
------------------------------------------------------------

-- Tabla de usuarios del sistema
CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  nombre VARCHAR(100),                                      -- Nombre completo del usuario
  correo VARCHAR(100),                                      -- Correo electrónico
  rol VARCHAR(50),                                          -- Rol del usuario (admin, editor, etc.)
  activo BOOLEAN,                                           -- Estado activo/inactivo
  fecha_creacion TIMESTAMP,                                 -- Fecha de creación del registro
  password_hash VARCHAR(255)                                -- Contraseña encriptada
);

-- Tabla de tipo de cambio oficial por fecha
CREATE TABLE tipo_cambio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  fecha DATE UNIQUE,                                        -- Fecha del tipo de cambio
  valor DECIMAL(10,4),                                      -- Valor del dólar en esa fecha
  fuente VARCHAR(100),                                      -- Fuente del dato (ej: Banco Central)
  usuario_registro_id BIGINT REFERENCES usuario(id),        -- Usuario que registró el dato
  fecha_registro TIMESTAMP                                  -- Fecha de registro
);

-- Tabla de parámetros comerciales vigentes (tipo de cambio y utilidad)
CREATE TABLE parametros_comerciales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  tipo_cambio_usado DECIMAL(10,4) CHECK (tipo_cambio_usado > 0),   -- Tipo de cambio positivo
  porcentaje_utilidad DECIMAL(5,2) CHECK (porcentaje_utilidad BETWEEN 0 AND 100), -- Margen válido
  fecha_vigencia DATE NOT NULL,                             -- Fecha desde la cual aplica
  usuario_editor_id BIGINT REFERENCES usuario(id),          -- Usuario que modificó el parámetro
  fecha_actualizacion TIMESTAMP DEFAULT NOW()               -- Fecha de modificación
);

-- Tabla de auditoría de parámetros comerciales
CREATE TABLE auditoria_parametros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  parametro VARCHAR(100) NOT NULL,                          -- Nombre del parámetro modificado
  valor_anterior VARCHAR(100),                              -- Valor previo
  valor_nuevo VARCHAR(100),                                 -- Valor nuevo
  usuario_id BIGINT REFERENCES usuario(id),                 -- Usuario que realizó el cambio
  fecha TIMESTAMP DEFAULT NOW()                             -- Fecha y hora del cambio
);

-- Tabla de clientes (barcos y operadores)
CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  nombre_barco VARCHAR(100) UNIQUE,                         -- Nombre del barco
  imo_numero VARCHAR(20),                                   -- Número IMO
  empresa_operadora VARCHAR(100),                           -- Empresa operadora
  correo_contacto VARCHAR(100),                             -- Correo de contacto
  puerto_base VARCHAR(100),                                 -- Puerto base
  pais_origen VARCHAR(50),                                  -- País de origen
  tipo_cliente VARCHAR(50),                                 -- Tipo de cliente
  capitán VARCHAR(100),                                     -- Nombre del capitán
  cocinero_jefe VARCHAR(100),                               -- Nombre del cocinero jefe
  observaciones TEXT,                                       -- Comentarios adicionales
  activo BOOLEAN,                                           -- Estado activo/inactivo
  fecha_creacion TIMESTAMP                                  -- Fecha de creación
);

-- Tabla de cotizaciones solicitadas por clientes
CREATE TABLE cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  cliente_id BIGINT REFERENCES cliente(id),                 -- Cliente asociado
  fecha_solicitud DATE,                                     -- Fecha de solicitud
  puerto_destino VARCHAR(100),                              -- Puerto de entrega
  archivo_origen VARCHAR(100),                              -- Archivo importado
  observaciones TEXT,                                       -- Comentarios adicionales
  usuario_importador_id BIGINT REFERENCES usuario(id),      -- Usuario que importó la cotización
  fecha_importacion TIMESTAMP                               -- Fecha de importación
);

-- Tabla de familias de productos
CREATE TABLE familia_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  nombre VARCHAR(100) UNIQUE,                               -- Nombre de la familia
  descripcion TEXT                                          -- Descripción
);

-- Tabla de productos disponibles
CREATE TABLE producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  familia_id BIGINT REFERENCES familia_producto(id),        -- Familia asociada
  descripcion_en TEXT,                                      -- Descripción en inglés
  descripcion_es TEXT,                                      -- Descripción en español
  unidad_medida VARCHAR(20),                                -- Unidad de medida
  valor_pesos DECIMAL(12,2),                                -- Valor en pesos
  fecha_actualizacion TIMESTAMP,                            -- Última actualización
  usuario_editor_id BIGINT REFERENCES usuario(id)           -- Usuario que editó el producto
);

-- Tabla de ítems dentro de una cotización
CREATE TABLE item_cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  cotizacion_id BIGINT REFERENCES cotizacion(id),           -- Cotización asociada
  producto_id BIGINT REFERENCES producto(id),               -- Producto asociado
  descripcion TEXT,                                         -- Descripción libre
  unidad_medida VARCHAR(20),                                -- Unidad de medida
  valor_pesos DECIMAL(12,2),                                -- Valor en pesos
  tipo_cambio_usado DECIMAL(10,4),                          -- Tipo de cambio aplicado
  precio_costo_neto DECIMAL(12,2),                          -- Precio costo USD
  porcentaje_utilidad DECIMAL(5,2),                         -- Margen aplicado
  precio_venta_neto DECIMAL(12,2),                          -- Precio final USD
  cantidad INT,                                             -- Cantidad solicitada
  total_neto DECIMAL(12,2),                                 -- Total neto del ítem
  comentarios TEXT                                          -- Comentarios adicionales
);

-- Tabla de auditoría de importaciones masivas
CREATE TABLE log_importacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Identificador único
  cotizacion_id BIGINT REFERENCES cotizacion(id),           -- Cotización importada
  usuario_id BIGINT REFERENCES usuario(id),                 -- Usuario que realizó la importación
  fecha TIMESTAMP,                                          -- Fecha del proceso
  total_items INT,                                          -- Total de ítems procesados
  items_vinculados INT,                                     -- Ítems vinculados correctamente
  items_no_encontrados INT,                                 -- Ítems no encontrados
  errores_detectados TEXT,                                  -- Errores técnicos
  resumen TEXT                                              -- Resumen general
);

------------------------------------------------------------
-- BLOQUE B — TABLAS DEL MODELO TOBE (SOLO ESTRUCTURA)
------------------------------------------------------------

-- Catálogo de brokers que envían cotizaciones
CREATE TABLE brokers (
    broker_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Identificador único
    broker_name VARCHAR(255) NOT NULL,                          -- Nombre del broker
    descripcion TEXT,                                           -- Descripción
    contacto VARCHAR(255),                                      -- Persona de contacto
    email VARCHAR(255),                                         -- Correo del broker
    activo BOOLEAN DEFAULT TRUE,                                -- Estado activo/inactivo
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         -- Fecha de creación
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP     -- Última actualización
);

-- Formatos de Excel por broker (permite versionado)
CREATE TABLE broker_formatos (
    formato_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Identificador único
    broker_id INTEGER NOT NULL,                                  -- Broker asociado
    version VARCHAR(50) DEFAULT '1.0',                           -- Versión del formato
    header_row INTEGER NOT NULL,                                 -- Fila donde empieza el header
    descripcion TEXT,                                            -- Descripción del formato
    archivo_ejemplo VARCHAR(500),                                -- Archivo de ejemplo
    activo BOOLEAN DEFAULT TRUE,                                 -- Estado activo/inactivo
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,          -- Fecha de creación
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP      -- Última actualización
);

-- Mapeo de columnas del formato a campos estándar
CREATE TABLE formato_columnas (
    columna_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Identificador único
    formato_id INTEGER NOT NULL,                                 -- Formato asociado
    campo_estandar VARCHAR(100) NOT NULL,                        -- Campo estándar (ITEM_NAME, etc.)
    nombre_columna_original VARCHAR(255),                        -- Nombre original en Excel
    indice_columna INTEGER NOT NULL,                             -- Índice 0-based
    letra_columna VARCHAR(10),                                   -- Letra de columna (A, B, C...)
    tipo_dato VARCHAR(50),                                       -- Tipo de dato esperado
    requerido BOOLEAN DEFAULT FALSE,                             -- Si es obligatorio
    descripcion TEXT,                                            -- Descripción del campo
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,          -- Fecha de creación
    color_fondo VARCHAR(20),                                     -- Color de fondo detectado
    color_texto VARCHAR(20),                                     -- Color del texto
    es_negrita BOOLEAN DEFAULT FALSE,                            -- Texto en negrita
    es_cursiva BOOLEAN DEFAULT FALSE,                            -- Texto en cursiva
    tiene_borde BOOLEAN DEFAULT FALSE                            -- Si tiene borde
);

-- Metadata adicional detectada en archivos
CREATE TABLE broker_metadata (
    metadata_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Identificador único
    formato_id INTEGER,                                            -- Formato asociado
    seccion VARCHAR(100),                                          -- Sección del archivo
    campo_nombre VARCHAR(100),                                     -- Nombre del campo
    campo_valor TEXT,                                              -- Valor detectado
    fila_origen INTEGER,                                           -- Fila donde se encontró
    columna_origen INTEGER,                                        -- Columna donde se encontró
    letra_columna VARCHAR(5),                                      -- Letra de columna
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP             -- Fecha de creación
);

-- Registro de archivos de cotización procesados
CREATE TABLE cotizaciones_archivos (
    archivo_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Identificador único
    broker_id INTEGER NOT NULL,                                  -- Broker asociado
    formato_id INTEGER,                                          -- Formato detectado
    nombre_archivo VARCHAR(500) NOT NULL,                        -- Nombre del archivo
    ruta_archivo TEXT,                                           -- Ruta en disco
    vessel_name VARCHAR(255),                                    -- Nombre del barco
    imo_number VARCHAR(50),                                      -- Número IMO
    numero_cotizacion VARCHAR(255),                              -- Número de cotización
    fecha_archivo DATE,                                          -- Fecha del archivo
    fecha_procesado TIMESTAMP DEFAULT CURRENT_TIMESTAMP          -- Fecha de procesamiento
);

-- Colores y estilos detectados en archivos
CREATE TABLE archivo_colores (
    color_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   -- Identificador único
    archivo_id INTEGER NOT NULL,                                 -- Archivo asociado
    campo_estandar VARCHAR(100) NOT NULL,                        -- Campo estándar
    nombre_columna_original VARCHAR(255),                        -- Nombre original
    indice_columna INTEGER NOT NULL,                             -- Índice de columna
    letra_columna VARCHAR(10),                                   -- Letra de columna
    color_fondo VARCHAR(20),                                     -- Color de fondo
    color_texto VARCHAR(20),                                     -- Color del texto
    es_negrita BOOLEAN DEFAULT FALSE,                            -- Negrita
    es_cursiva BOOLEAN DEFAULT FALSE,                            -- Cursiva
    tiene_borde BOOLEAN DEFAULT FALSE,                           -- Borde
    fecha_deteccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP          -- Fecha de detección
);

------------------------------------------------------------
-- FIN DEL SCRIPT MAESTRO (OPCIÓN B)
------------------------------------------------------------






