-- Tabla de usuarios del sistema
CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único
  nombre VARCHAR(100),                                    -- Nombre completo
  correo VARCHAR(100),                                    -- Correo electrónico
  rol VARCHAR(50),                                        -- Rol del usuario (admin, editor, etc.)
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP,                               -- Fecha de creación del usuario
  password_hash VARCHAR(255)                              -- Contraseña encriptada
);

-- Tabla de tipo de cambio oficial por fecha
CREATE TABLE tipo_cambio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE UNIQUE,                                      -- Fecha del tipo de cambio
  valor DECIMAL(10,4),                                    -- Valor del dólar en esa fecha
  fuente VARCHAR(100),                                    -- Fuente del dato (ej: Banco Central)
  usuario_registro_id BIGINT REFERENCES usuario(id),      -- Usuario que registró el dato
  fecha_registro TIMESTAMP                                -- Fecha de registro
);

-- Tabla de parámetros comerciales vigentes (tipo de cambio y utilidad)
CREATE TABLE parametros_comerciales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cambio_usado DECIMAL(10,4) CHECK (tipo_cambio_usado > 0),   -- Tipo de cambio positivo
  porcentaje_utilidad DECIMAL(5,2) CHECK (porcentaje_utilidad BETWEEN 0 AND 100), -- Margen válido
  fecha_vigencia DATE NOT NULL,                                    -- Fecha desde la cual aplica
  usuario_editor_id BIGINT REFERENCES usuario(id),                 -- Usuario que modificó el parámetro
  fecha_actualizacion TIMESTAMP DEFAULT NOW()                      -- Fecha de modificación
);

-- Tabla de auditoría de parámetros comerciales
CREATE TABLE auditoria_parametros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único
  parametro VARCHAR(100) NOT NULL,                        -- Nombre del parámetro
  valor_anterior VARCHAR(100),                            -- Valor anterior
  valor_nuevo VARCHAR(100),                               -- Valor nuevo
  usuario_id BIGINT REFERENCES usuario(id),               -- Usuario que realizó el cambio
  fecha TIMESTAMP DEFAULT NOW()                           -- Fecha y hora del cambio
);

-- Tabla de clientes (barcos y operadores)
CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_barco VARCHAR(100) UNIQUE,                       -- Nombre del barco
  imo_numero VARCHAR(20),                                 -- Número IMO
  empresa_operadora VARCHAR(100),                         -- Empresa que opera el barco
  correo_contacto VARCHAR(100),                           -- Correo de contacto
  puerto_base VARCHAR(100),                               -- Puerto base del barco
  pais_origen VARCHAR(50),                                -- País de origen
  tipo_cliente VARCHAR(50),                               -- Tipo de cliente
  capitán VARCHAR(100),                                   -- Nombre del capitán
  cocinero_jefe VARCHAR(100),                             -- Nombre del cocinero jefe
  observaciones TEXT,                                     -- Comentarios adicionales
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP                                -- Fecha de creación del cliente
);

-- Tabla de cotizaciones solicitadas por clientes
CREATE TABLE cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES cliente(id),               -- Cliente que solicita la cotización
  fecha_solicitud DATE,                                   -- Fecha de solicitud
  puerto_destino VARCHAR(100),                            -- Puerto de entrega
  archivo_origen VARCHAR(100),                            -- Nombre del archivo importado
  observaciones TEXT,                                     -- Comentarios adicionales
  usuario_importador_id BIGINT REFERENCES usuario(id),    -- Usuario que importó la cotización
  fecha_importacion TIMESTAMP                             -- Fecha de importación
);

-- Tabla de familias de productos
CREATE TABLE familia_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) UNIQUE,                             -- Nombre de la familia
  descripcion TEXT                                        -- Descripción de la familia
);

-- Tabla de productos disponibles
CREATE TABLE producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  familia_id BIGINT REFERENCES familia_producto(id),      -- Familia a la que pertenece
  descripcion_en TEXT,                                    -- Descripción en inglés
  descripcion_es TEXT,                                    -- Descripción en español
  unidad_medida VARCHAR(20),                              -- Unidad de medida
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos
  fecha_actualizacion TIMESTAMP,                          -- Fecha de última modificación
  usuario_editor_id BIGINT REFERENCES usuario(id)         -- Usuario que editó el producto
);

-- Tabla de ítems dentro de una cotización
CREATE TABLE item_cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización a la que pertenece
  producto_id BIGINT REFERENCES producto(id),             -- Producto vinculado
  descripcion TEXT,                                       -- Descripción libre del ítem
  unidad_medida VARCHAR(20),                              -- Unidad de medida
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos
  tipo_cambio_usado DECIMAL(10,4),                        -- Tipo de cambio aplicado
  precio_costo_neto DECIMAL(12,2),                        -- Precio de costo en USD
  porcentaje_utilidad DECIMAL(5,2),                       -- Margen aplicado
  precio_venta_neto DECIMAL(12,2),                        -- Precio final en USD
  cantidad INT,                                           -- Cantidad solicitada
  total_neto DECIMAL(12,2),                               -- Total neto del ítem
  comentarios TEXT                                        -- Comentarios adicionales
);

-- Tabla de auditoría de importaciones masivas
CREATE TABLE log_importacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización importada
  usuario_id BIGINT REFERENCES usuario(id),               -- Usuario que realizó la importación
  fecha TIMESTAMP,                                        -- Fecha del proceso
  total_items INT,                                        -- Total de ítems procesados
  items_vinculados INT,                                   -- Ítems vinculados correctamente
  items_no_encontrados INT,                               -- Ítems no encontrados en catálogo
  errores_detectados TEXT,                                -- Errores técnicos o de formato
  resumen TEXT                                            -- Resumen general del proceso
);

------------------------------------------------------------
-- BLOQUE A — TABLAS DEL SISTEMA ( MODELO DITTO)
------------------------------------------------------------

-- Tabla de usuarios del sistema
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    correo VARCHAR(100),
    rol VARCHAR(50),
    activo BOOLEAN,
    fecha_creacion TIMESTAMP,
    password_hash VARCHAR(255)
);

-- Tabla de tipo de cambio oficial por fecha
CREATE TABLE tipo_cambio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE UNIQUE,
    valor DECIMAL(10,4),
    fuente VARCHAR(100),
    usuario_registro_id BIGINT REFERENCES usuario(id),
    fecha_registro TIMESTAMP
);

-- Tabla de parámetros comerciales vigentes
CREATE TABLE parametros_comerciales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cambio_usado DECIMAL(10,4) CHECK (tipo_cambio_usado > 0),
    porcentaje_utilidad DECIMAL(5,2) CHECK (porcentaje_utilidad BETWEEN 0 AND 100),
    fecha_vigencia DATE NOT NULL,
    usuario_editor_id BIGINT REFERENCES usuario(id),
    fecha_actualizacion TIMESTAMP DEFAULT NOW()
);

-- Tabla de auditoría de parámetros comerciales
CREATE TABLE auditoria_parametros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametro VARCHAR(100) NOT NULL,
    valor_anterior VARCHAR(100),
    valor_nuevo VARCHAR(100),
    usuario_id BIGINT REFERENCES usuario(id),
    fecha TIMESTAMP DEFAULT NOW()
);

-- Tabla de clientes
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_barco VARCHAR(100) UNIQUE,
    imo_numero VARCHAR(20),
    empresa_operadora VARCHAR(100),
    correo_contacto VARCHAR(100),
    puerto_base VARCHAR(100),
    pais_origen VARCHAR(50),
    tipo_cliente VARCHAR(50),
    capitán VARCHAR(100),
    cocinero_jefe VARCHAR(100),
    observaciones TEXT,
    activo BOOLEAN,
    fecha_creacion TIMESTAMP
);

-- Tabla de cotizaciones
CREATE TABLE cotizacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES cliente(id),
    fecha_solicitud DATE,
    puerto_destino VARCHAR(100),
    archivo_origen VARCHAR(100),
    observaciones TEXT,
    usuario_importador_id BIGINT REFERENCES usuario(id),
    fecha_importacion TIMESTAMP
);

-- Tabla de familias de productos
CREATE TABLE familia_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE,
    descripcion TEXT
);

-- Tabla de productos disponibles
CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    familia_id BIGINT REFERENCES familia_producto(id),
    descripcion_en TEXT,
    descripcion_es TEXT,
    unidad_medida VARCHAR(20),
    valor_pesos DECIMAL(12,2),
    fecha_actualizacion TIMESTAMP,
    usuario_editor_id BIGINT REFERENCES usuario(id)
);

------------------------------------------------------------
-- *** NUEVA TABLA INTEGRADA ***
-- Tabla de sinónimos de productos
------------------------------------------------------------

CREATE TABLE producto_sinonimo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto(id),
    nombre_sinonimo TEXT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT NOW(),
    usuario VARCHAR(100)
);

-- Índices recomendados
CREATE INDEX idx_sinonimo_producto ON producto_sinonimo (producto_id);
CREATE INDEX idx_sinonimo_nombre ON producto_sinonimo (nombre_sinonimo);

------------------------------------------------------------

-- Tabla de ítems dentro de una cotización
CREATE TABLE item_cotizacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id BIGINT REFERENCES cotizacion(id),
    producto_id BIGINT REFERENCES producto(id),
    descripcion TEXT,
    unidad_medida VARCHAR(20),
    valor_pesos DECIMAL(12,2),
    tipo_cambio_usado DECIMAL(10,4),
    precio_costo_neto DECIMAL(12,2),
    porcentaje_utilidad DECIMAL(5,2),
    precio_venta_neto DECIMAL(12,2),
    cantidad INT,
    total_neto DECIMAL(12,2),
    comentarios TEXT
);

-- Tabla de auditoría de importaciones masivas
CREATE TABLE log_importacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id BIGINT REFERENCES cotizacion(id),
    usuario_id BIGINT REFERENCES usuario(id),
    fecha TIMESTAMP,
    total_items INT,
    items_vinculados INT,
    items_no_encontrados INT,
    errores_detectados TEXT,
    resumen TEXT
);

------------------------------------------------------------
-- BLOQUE B — TABLAS DEL MODELO TOBE (SOLO ESTRUCTURA)
------------------------------------------------------------

-- Catálogo de brokers
CREATE TABLE brokers (
    broker_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    broker_name VARCHAR(255) NOT NULL,
    descripcion TEXT,
    contacto VARCHAR(255),
    email VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Formatos de Excel por broker
CREATE TABLE broker_formatos (
    formato_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    broker_id INTEGER NOT NULL,
    version VARCHAR(50) DEFAULT '1.0',
    header_row INTEGER NOT NULL,
    descripcion TEXT,
    archivo_ejemplo VARCHAR(500),
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Mapeo de columnas del formato
CREATE TABLE formato_columnas (
    columna_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    formato_id INTEGER NOT NULL,
    campo_estandar VARCHAR(100) NOT NULL,
    nombre_columna_original VARCHAR(255),
    indice_columna INTEGER NOT NULL,
    letra_columna VARCHAR(10),
    tipo_dato VARCHAR(50),
    requerido BOOLEAN DEFAULT FALSE,
    descripcion TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    color_fondo VARCHAR(20),
    color_texto VARCHAR(20),
    es_negrita BOOLEAN DEFAULT FALSE,
    es_cursiva BOOLEAN DEFAULT FALSE,
    tiene_borde BOOLEAN DEFAULT FALSE
);

-- Metadata adicional
CREATE TABLE broker_metadata (
    metadata_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    formato_id INTEGER,
    seccion VARCHAR(100),
    campo_nombre VARCHAR(100),
    campo_valor TEXT,
    fila_origen INTEGER,
    columna_origen INTEGER,
    letra_columna VARCHAR(5),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Registro de archivos procesados
CREATE TABLE cotizaciones_archivos (
    archivo_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    broker_id INTEGER NOT NULL,
    formato_id INTEGER,
    nombre_archivo VARCHAR(500) NOT NULL,
    ruta_archivo TEXT,
    vessel_name VARCHAR(255),
    imo_number VARCHAR(50),
    numero_cotizacion VARCHAR(255),
    fecha_archivo DATE,
    fecha_procesado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Colores detectados
CREATE TABLE archivo_colores (
    color_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    archivo_id INTEGER NOT NULL,
    campo_estandar VARCHAR(100) NOT NULL,
    nombre_columna_original VARCHAR(255),
    indice_columna INTEGER NOT NULL,
    letra_columna VARCHAR(10),
    color_fondo VARCHAR(20),
    color_texto VARCHAR(20),
    es_negrita BOOLEAN DEFAULT FALSE,
    es_cursiva BOOLEAN DEFAULT FALSE,
    tiene_borde BOOLEAN DEFAULT FALSE,
    fecha_deteccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------
-- FIN DEL MODELO COMPLETO
------------------------------------------------------------
