-- Tabla de usuarios del sistema
CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único
  nombre VARCHAR(100),                                    -- Nombre completo
  correo VARCHAR(100),                                    -- Correo electrónico
  rol VARCHAR(50),                                        -- Rol del usuario (admin, editor, etc.)
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP                                -- Fecha de creación del usuario
);

-- Tabla de tipo de cambio oficial por fecha
CREATE TABLE tipo_cambio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE UNIQUE,                                      -- Fecha del tipo de cambio
  valor DECIMAL(10,4),                                    -- Valor del dólar en esa fecha
  fuente VARCHAR(100),                                    -- Fuente del dato (ej: Banco Central)
  usuario_registro_id BIGINT REFERENCES usuario(id),      -- Usuario que registró el dato
  fecha_registro TIMESTAMP                                -- Fecha de registro
);

-- Tabla de parámetros comerciales vigentes (tipo de cambio y utilidad)
CREATE TABLE parametros_comerciales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cambio_usado DECIMAL(10,4),                        -- Tipo de cambio vigente para cálculos
  porcentaje_utilidad DECIMAL(5,2),                       -- Margen de utilidad aplicado
  fecha_vigencia DATE NOT NULL,                           -- Fecha desde la cual aplica
  usuario_editor_id BIGINT REFERENCES usuario(id),        -- Usuario que modificó el parámetro
  fecha_actualizacion TIMESTAMP DEFAULT NOW()             -- Fecha de modificación
);

-- Tabla de clientes (barcos y operadores)
CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_barco VARCHAR(100) UNIQUE,                       -- Nombre del barco
  imo_numero VARCHAR(20),                                 -- Número IMO
  empresa_operadora VARCHAR(100),                         -- Empresa que opera el barco
  correo_contacto VARCHAR(100),                           -- Correo de contacto
  puerto_base VARCHAR(100),                               -- Puerto base del barco
  pais_origen VARCHAR(50),                                -- País de origen
  tipo_cliente VARCHAR(50),                               -- Tipo de cliente (charter, flota, etc.)
  capitán VARCHAR(100),                                   -- Nombre del capitán
  cocinero_jefe VARCHAR(100),                             -- Nombre del cocinero jefe
  observaciones TEXT,                                     -- Comentarios adicionales
  activo BOOLEAN,                                         -- Estado activo/inactivo
  fecha_creacion TIMESTAMP                                -- Fecha de creación del cliente
);

-- Tabla de cotizaciones solicitadas por clientes
CREATE TABLE cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES cliente(id),               -- Cliente que solicita la cotización
  fecha_solicitud DATE,                                   -- Fecha de solicitud
  puerto_destino VARCHAR(100),                            -- Puerto de entrega
  archivo_origen VARCHAR(100),                            -- Nombre del archivo importado
  observaciones TEXT,                                     -- Comentarios adicionales
  usuario_importador_id BIGINT REFERENCES usuario(id),    -- Usuario que importó la cotización
  fecha_importacion TIMESTAMP                             -- Fecha de importación
);

-- Tabla de familias de productos
CREATE TABLE familia_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) UNIQUE,                             -- Nombre de la familia (ej: Lácteos)
  descripcion TEXT                                        -- Descripción de la familia
);

-- Tabla de productos disponibles
CREATE TABLE producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  familia_id BIGINT REFERENCES familia_producto(id),      -- Familia a la que pertenece el producto
  descripcion_en TEXT,                                    -- Descripción en inglés
  descripcion_es TEXT,                                    -- Descripción en español
  unidad_medida VARCHAR(20),                              -- Unidad de medida (ej: kg, litro)
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos (precio base)
  fecha_actualizacion TIMESTAMP,                          -- Fecha de última modificación
  usuario_editor_id BIGINT REFERENCES usuario(id)         -- Usuario que editó el producto
);

-- Tabla de ítems dentro de una cotización
CREATE TABLE item_cotizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización a la que pertenece
  producto_id BIGINT REFERENCES producto(id),             -- Producto vinculado (puede ser nulo)
  descripcion TEXT,                                       -- Descripción libre del ítem
  unidad_medida VARCHAR(20),                              -- Unidad de medida
  valor_pesos DECIMAL(12,2),                              -- Valor en pesos
  tipo_cambio_usado DECIMAL(10,4),                        -- Tipo de cambio aplicado
  precio_costo_neto DECIMAL(12,2),                        -- Precio de costo en USD
  porcentaje_utilidad DECIMAL(5,2),                       -- Margen aplicado
  precio_venta_neto DECIMAL(12,2),                        -- Precio final en USD
  cantidad INT,                                           -- Cantidad solicitada
  total_neto DECIMAL(12,2),                               -- Total neto del ítem
  comentarios TEXT                                        -- Comentarios adicionales
);

-- Tabla de auditoría de importaciones masivas
CREATE TABLE log_importacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT REFERENCES cotizacion(id),         -- Cotización importada
  usuario_id BIGINT REFERENCES usuario(id),               -- Usuario que realizó la importación
  fecha TIMESTAMP,                                        -- Fecha del proceso
  total_items INT,                                        -- Total de ítems procesados
  items_vinculados INT,                                   -- Ítems que se vincularon correctamente
  items_no_encontrados INT,                               -- Ítems que no se encontraron en catálogo
  errores_detectados TEXT,                                -- Errores técnicos o de formato
  resumen TEXT                                            -- Resumen general del proceso
);
