

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: brokers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (1, 'OCEANIC CATERING LTD', NULL, NULL, NULL, true, '2025-12-20 16:19:03.13888', '2025-12-20 16:19:03.13888');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (2, 'MCTC MARINE LTD', NULL, NULL, NULL, true, '2025-12-20 16:19:03.194466', '2025-12-20 16:19:03.194466');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (3, 'CMA CGM', NULL, NULL, NULL, true, '2025-12-20 16:19:03.252571', '2025-12-20 16:19:03.252571');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (4, 'PROCURESHIP', NULL, NULL, NULL, true, '2025-12-20 16:19:03.30053', '2025-12-20 16:19:03.30053');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (5, 'GARRETS INTERNATIONAL LTD', NULL, NULL, NULL, true, '2025-12-20 16:19:03.361828', '2025-12-20 16:19:03.361828');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (6, 'BSM CATERING', NULL, NULL, NULL, true, '2025-12-20 17:01:09.298952', '2025-12-20 17:01:09.298952');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (7, 'MSC SHIPMANAGEMENT', NULL, NULL, NULL, true, '2025-12-20 17:01:09.300703', '2025-12-20 17:01:09.300703');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (8, 'ANGLO EASTERN', NULL, NULL, NULL, true, '2025-12-20 17:01:09.301657', '2025-12-20 17:01:09.301657');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (9, 'UMAR', NULL, NULL, NULL, true, '2025-12-20 17:01:10.455409', '2025-12-20 17:01:10.455409');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (10, 'BERNHARD SCHULTE', NULL, NULL, NULL, true, '2025-12-20 17:01:10.585628', '2025-12-20 17:01:10.585628');
INSERT INTO public.brokers (broker_id, broker_name, descripcion, contacto, email, activo, fecha_creacion, fecha_actualizacion) VALUES (11, 'OPERATION3', NULL, NULL, NULL, true, '2025-12-20 17:01:10.669084', '2025-12-20 17:01:10.669084');


--
-- Data for Name: broker_formatos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (7, 6, '1.0', 18, NULL, 'RFQ_EQ_SCF_CISA_0152.xlsm', true, '2025-12-28 22:39:07.756278', '2026-01-24 23:43:02.938648');
INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (1, 1, '1.0', 12, NULL, 'OAS1210RO008910122025150143766.xlsx', true, '2025-12-20 16:19:03.13888', '2026-01-24 23:43:03.078442');
INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (2, 2, '1.0', 9, NULL, 'QTN_LOU_233.xlsx', true, '2025-12-20 16:19:03.194466', '2026-01-24 23:43:03.136574');
INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (3, 3, '1.0', 18, NULL, '2679-2025R-0342-1293695-124805 (1).xlsx', true, '2025-12-20 16:19:03.252571', '2026-01-24 23:43:03.233725');
INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (4, 4, '1.0', 13, NULL, 'ATRA-ST-25-104_3_Valparaiso Ship Services SA (1).xlsx', true, '2025-12-20 16:19:03.30053', '2026-01-24 23:43:03.325219');
INSERT INTO public.broker_formatos (formato_id, broker_id, version, header_row, descripcion, archivo_ejemplo, activo, fecha_creacion, fecha_actualizacion) VALUES (5, 5, '1.0', 24, NULL, 'quotation_RFQ0204875.xlsx', true, '2025-12-20 16:19:03.361828', '2026-01-24 23:43:03.432201');


--
-- Data for Name: broker_metadata; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (321, 7, 'Company Details', 'Company Name Line 1', 'BERNHARD SCHULTE SHIPMANAGEMENT (SINGAPORE) PTE. LTD.', 3, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (322, 7, 'Company Details', 'Company Name Line 2', 'BSM - CATERING SERVICES,', 4, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (323, 7, 'Company Details', 'Company Name Line 3', 'BERNHARD SCHULTE SHIPMANAGEMENT (L) LTD.,', 5, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (324, 7, 'Company Details', 'Company Name Line 4', 'C\O Bernhard Schulte Shipmanagement (India) Pvt. Limited', 6, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (325, 7, 'Company Details', 'Company Address', '401 Olympia, Hiranandani Gardens, Powai, Mumbai 400 076, India', 7, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (326, 7, 'Company Details', 'Company Contact', 'Tel: +91-22-40017300        Fax: +91-22-40017555', 8, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (327, 7, 'Company Details', 'Company Email Label', 'Email:', 9, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (328, 7, 'Company Details', 'Company Email', 'seachef@seachef.com', 9, 2, 'C', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (329, 7, 'Company Details', 'Company Web Label', 'Web:', 10, 0, 'A', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (330, 7, 'Company Details', 'Company Web', 'www.seachef.com /  www.bs-shipmanagement.com', 10, 2, 'C', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (331, 7, 'RFQ Information', 'Vessel', 'MSC Lome V', 3, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (332, 7, 'RFQ Information', 'RFQ Number', 'EQ/SCF/CISA/0152', 4, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (333, 7, 'RFQ Information', 'RFQ Date', 'Fri Oct 24 00:00:00 CLST 2025', 5, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (334, 7, 'RFQ Information', 'Submit Quote Before', 'Fri Oct 24 00:00:00 CLST 2025', 7, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (335, 7, 'RFQ Information', 'Port of Delivery', 'Port of Delivery', 8, 11, 'L', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (336, 7, 'RFQ Information', 'Vessel ETA', 'Fri Oct 31 12:00:00 CLST 2025', 9, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (337, 7, 'RFQ Information', 'Payment Terms', 'Credit', 10, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (338, 7, 'RFQ Information', 'Payment Days', '7', 10, 18, 'S', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (339, 7, 'RFQ Information', 'Vendor Reference', 'Vendor Reference', 11, 12, 'M', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (340, 7, 'RFQ Information', 'Delivery Term', 'Free On Board', 12, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (341, 7, 'RFQ Information', 'Currency', 'USD', 13, 14, 'O', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (342, 7, 'RFQ Information', 'Discount Percentage', 'Discount (%) for all items', 14, 12, 'M', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (343, 7, 'RFQ Information', 'VAT Percentage', 'VAT(%) for all items', 15, 12, 'M', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (344, 7, 'RFQ Information', 'Place City', 'Place (CITY)', 16, 12, 'M', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (345, 7, 'Vendor Details', 'Vendor Name', 'Valparaiso Ship Services S.A.', 12, 3, 'D', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (346, 7, 'Vendor Details', 'Vendor Address', 'Calle Tercera N°820 , Placilla, Valparaiso', 13, 3, 'D', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (347, 7, 'Vendor Details', 'Vendor Phone', '56 32 2298972', 15, 3, 'D', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (348, 7, 'Vendor Details', 'Vendor Email', 'vss@vsschile.cl', 16, 3, 'D', '2026-01-24 23:43:02.958183');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (355, 2, 'Quotation Header', 'Vessel Name', 'Louise Auerbach', 1, 4, 'E', '2026-01-24 23:43:03.15561');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (356, 2, 'Quotation Header', 'IMO Number', '9388895', 2, 4, 'E', '2026-01-24 23:43:03.15561');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (357, 2, 'Quotation Header', 'Port of Delivery', 'SFO/LOU/56', 3, 4, 'E', '2026-01-24 23:43:03.15561');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (358, 2, 'Quotation Header', 'Quotation Number', 'QTN/LOU/233', 7, 3, 'D', '2026-01-24 23:43:03.15561');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (367, 4, 'Requisition Information', 'IMO Number', 'Buyer', 3, 1, 'B', '2026-01-24 23:43:03.355499');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (368, 4, 'Requisition Information', 'Requisition Number', 'UNISEA SHIPPING LTD.', 4, 1, 'B', '2026-01-24 23:43:03.355499');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (369, 4, 'Requisition Information', 'Port', '4 Xenias Str', 5, 1, 'B', '2026-01-24 23:43:03.355499');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (370, 4, 'Requisition Information', 'ETA Date', '14562 Greece', 6, 1, 'B', '2026-01-24 23:43:03.355499');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (388, 3, 'RFQ Information', 'Vessel', 'CMA CGM MEKONG', 1, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (389, 3, 'RFQ Information', 'RFQ No.', '2679-2025R-0341', 2, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (390, 3, 'RFQ Information', 'RFQ Date', '17-Dec-2025', 3, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (391, 3, 'RFQ Information', 'Req No(s)', '2679-2025R-0341', 4, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (392, 3, 'RFQ Information', 'Submit Quote Before', '17-Dec-2025', 5, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (393, 3, 'RFQ Information', 'Port of Delivery', 'SAN ANTONIO', 6, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (394, 3, 'RFQ Information', 'Delivery Date', '2-Jan-2026', 7, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (395, 3, 'RFQ Information', 'Vendor Reference', '', 8, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (396, 3, 'RFQ Information', 'Select Currency', '', 10, 2, 'C', '2026-01-25 21:13:15.796333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (429, 2, 'Quotation Header', 'Vessel Name', 'Polar Argentina', 1, 4, 'E', '2026-01-25 21:23:20.652053');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (430, 2, 'Quotation Header', 'IMO Number', '9797204', 2, 4, 'E', '2026-01-25 21:23:20.652053');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (431, 2, 'Quotation Header', 'Port of Delivery', 'SFO/APL/70', 3, 4, 'E', '2026-01-25 21:23:20.652053');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (432, 2, 'Quotation Header', 'Quotation Number', 'QTN/APL/252', 7, 3, 'D', '2026-01-25 21:23:20.652053');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (349, 1, 'Company Information', 'Company Name', 'OCL Oceanic Catering Ltd', 0, 0, 'A', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (350, 1, 'Request Information', 'Quotation Request Number', 'OAS/1210/RO0089', 4, 2, 'C', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (351, 1, 'Request Information', 'Quotation Request Date', 'Wed Dec 10 00:00:00 CLST 2025', 5, 2, 'C', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (352, 1, 'Request Information', 'Est. Delivery Date', 'Wed Dec 10 00:00:00 CLST 2025', 6, 2, 'C', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (353, 1, 'Request Information', 'Loading Port', 'QUINTERO, Chile', 7, 2, 'C', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (354, 1, 'Request Information', 'Vessel', 'SEAWAYS ATHENS', 8, 2, 'C', '2026-01-24 23:43:03.091287');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (397, 5, 'Buyer Information', 'Buyer Info', 'Buyer Info:', 0, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (398, 5, 'Buyer Information', 'Company Name', 'Garrets International Limited', 1, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (399, 5, 'Buyer Information', 'Company Address', '27-43 Eastern Road, 3rd Floor South Wing, St James House Romford', 1, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (400, 5, 'Buyer Information', 'Company Phone', '+4401708740400', 1, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (401, 5, 'Buyer Information', 'Contact Name', 'Edgar Quinagoran', 1, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (402, 5, 'Buyer Information', 'Contact Email', 'fleet1asia@garrets.com', 1, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (403, 5, 'Buyer Information', 'Contact Phone', '', 2, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (404, 5, 'Buyer Information', 'Contact Email Alt', 'Fleet1Asia@Garrets.com', 3, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (371, 5, 'RFQ Information', 'Document Title', 'Buyer Info:', 0, 0, 'A', '2026-01-24 23:43:03.448997');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (405, 5, 'Buyer Information', 'Contact Fax', '', 4, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (406, 5, 'RFQ Information', 'RFQ Title', 'REQUEST FOR QUOTATION', 6, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (407, 5, 'RFQ Information', 'RFQ Number', 'RFQ0204875', 6, 8, 'I', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (408, 5, 'RFQ Information', 'Generated On', '12/11/2025', 6, 11, 'L', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (409, 5, 'RFQ Information', 'Respond By', '12/12/2025 09:00', 14, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (410, 5, 'RFQ Information', 'Issue Date', '12/11/2025', 14, 4, 'E', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (411, 5, 'RFQ Information', 'Delivery Required By', '12/25/2025', 14, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (412, 5, 'RFQ Information', 'Vendor Quotation Reference', '', 15, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (413, 5, 'RFQ Information', 'Port', 'VALPARAISO', 15, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (414, 5, 'RFQ Information', 'Packaging Cost', '', 16, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (415, 5, 'RFQ Information', 'Ship to', '', 16, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (416, 5, 'RFQ Information', 'Currency', 'USD', 17, 4, 'E', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (417, 5, 'RFQ Information', 'Ship Name', 'VECCO', 17, 10, 'K', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (418, 5, 'RFQ Information', 'IMO Number', '9696852', 17, 11, 'L', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (419, 5, 'RFQ Information', 'Freight', '', 18, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (380, 3, 'Company Details', 'RFQ Label', 'RFQ_', 0, 1, 'B', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (381, 3, 'Company Details', 'Company Name', 'CMA SHIPS SAS', 3, 0, 'A', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (382, 3, 'Company Details', 'Company Info', '4 QUAI D''ARENC
 PHONE :+ 33 4 88 91 9000
 FAX :
 Website :
 Email :', 4, 0, 'A', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (383, 3, 'Vendor Details', 'Vendor Name', 'VALPARAISO SHIP SERVICES S.A.', 12, 3, 'D', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (384, 3, 'Vendor Details', 'Vendor Address', 'CALLE TERCERA 820
3100000', 13, 3, 'D', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (385, 3, 'Vendor Details', 'Vendor City', 'PLACILLA', 14, 3, 'D', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (386, 3, 'Vendor Details', 'Vendor Phone', '323321310', 15, 3, 'D', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (387, 3, 'Vendor Details', 'Vendor Email', 'vss@vsschile.cl, valpoship@gmail.com', 16, 3, 'D', '2026-01-25 21:09:52.752333');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (420, 5, 'RFQ Information', 'Remarks', '', 19, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (421, 5, 'RFQ Information', 'Seller Remarks', '', 19, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (422, 5, 'Supplier Information', 'Supplier Info', 'Supplier Info:', 8, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (423, 5, 'Supplier Information', 'Supplier Name', 'Valparaiso Ship Services Sa', 9, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (424, 5, 'Supplier Information', 'Supplier Address', 'Calle Tercera No. 820 Placilla', 9, 0, 'A', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (425, 5, 'Supplier Information', 'Contact', 'Contact', 9, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (426, 5, 'Supplier Information', 'Contact Phone', '+56322299110', 10, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (427, 5, 'Supplier Information', 'Contact Email', 'vss@valparaisoshipservice.cl', 11, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (428, 5, 'Supplier Information', 'Contact Fax', '511/578-2823', 12, 9, 'J', '2026-01-25 21:19:00.379062');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (433, 4, 'Buyer Information', 'Buyer', 'UNISEA SHIPPING LTD.', 4, 1, 'B', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (434, 4, 'Buyer Information', 'Buyer Address 1', '4 Xenias Str', 5, 1, 'B', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (435, 4, 'Buyer Information', 'Buyer Address 2', '14562 Greece', 6, 1, 'B', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (436, 4, 'RFQ Information', 'Requisition No', 'ATRA-ST-25-103/3', 4, 7, 'H', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (437, 4, 'RFQ Information', 'Requisition Date', '07/11/2025', 5, 7, 'H', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (438, 4, 'RFQ Information', 'Delivery Due Date', '01/12/2025', 6, 7, 'H', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (439, 4, 'RFQ Information', 'Quote Before', '01/12/2025', 7, 7, 'H', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (440, 4, 'RFQ Information', 'Delivery Port', 'Quintero, Chile', 4, 10, 'K', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (441, 4, 'RFQ Information', 'Vessel', 'AQUATRAVESIA', 5, 10, 'K', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (442, 4, 'RFQ Information', 'IMO', '9785732', 6, 10, 'K', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (443, 4, 'RFQ Information', 'Yard', 'SAMSUNG HEAVY INDUSTRIES', 7, 10, 'K', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (444, 4, 'RFQ Information', 'Year Built', '2017', 8, 10, 'K', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (445, 4, 'Supplier Information', 'Supplier Name', 'Valparaiso Ship Services SA', 4, 15, 'P', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (446, 4, 'Supplier Information', 'Supplier Address 1', 'calle tercera 820 placilla', 5, 15, 'P', '2026-01-25 21:34:50.026682');
INSERT INTO public.broker_metadata (metadata_id, formato_id, seccion, campo_nombre, campo_valor, fila_origen, columna_origen, letra_columna, fecha_creacion) VALUES (447, 4, 'Supplier Information', 'Supplier Address 2', '2340000 Chile', 6, 15, 'P', '2026-01-25 21:34:50.026682');


--
-- Data for Name: formato_columnas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1059, 3, 'LINE_NO', 'No', 0, 'A', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1060, 3, 'ITEM_CODE', 'Item Code', 2, 'C', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1061, 3, 'DESCRIPTION', 'Description', 3, 'D', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1062, 3, 'BRAND', 'Brand', 5, 'F', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1063, 3, 'WEIGHT', 'Weight', 6, 'G', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1064, 3, 'UOM', 'Unit', 7, 'H', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1065, 3, 'PACKAGE', 'Package', 8, 'I', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1066, 3, 'QUANTITY', 'Quantity', 9, 'J', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1067, 3, 'UNIT_PRICE', 'Unit Price (  )', 10, 'K', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1068, 3, 'TOTAL_LINE', 'Total Line', 11, 'L', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1069, 3, 'DISCOUNT', 'Discount %', 12, 'M', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1070, 3, 'VAT', 'VAT %', 13, 'N', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1071, 3, 'TOTAL', 'Total Price', 14, 'O', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1072, 3, 'VENDOR_REMARKS', 'Vendor Remarks', 15, 'P', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1073, 3, 'OFFICE_REMARKS', 'Office Remarks', 17, 'R', NULL, false, NULL, '2026-01-25 21:01:14.122671', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1075, 2, 'LINE_NO', 'AA', 0, 'A', NULL, false, NULL, '2026-01-25 21:27:50.425154', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1076, 2, 'VESSEL_COMMENTS', 'VESSEL COMMENTS', 9, 'J', NULL, false, NULL, '2026-01-25 21:27:50.425154', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1081, 4, 'LINE_NO', 'No.', 1, 'B', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1082, 4, 'DESCRIPTION', 'Description', 2, 'C', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1083, 4, 'OFFICE_NOTES', 'Item Office Notes', 3, 'D', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1084, 4, 'VESSEL_NOTES', 'Vessel Notes', 4, 'E', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1085, 4, 'ITEM_CODE', 'Item Code / Part No.', 5, 'F', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1086, 4, 'REFERENCE_NO', 'Reference No.', 6, 'G', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1087, 4, 'DRAWING_NO', 'Drawing No.', 7, 'H', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1088, 4, 'QUANTITY_REQUESTED', 'Quantity Requested', 8, 'I', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1089, 4, 'UOM', 'UoM', 9, 'J', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1090, 4, 'QUANTITY_OFFERED', 'Quantity Offered', 10, 'K', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1091, 4, 'UOM_OFFERED', 'UoM', 11, 'L', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1092, 4, 'UNIT_PRICE', 'Unit Cost', 12, 'M', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1093, 4, 'DISCOUNT', 'Disc. %', 13, 'N', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1094, 4, 'TOTAL', 'Line Cost', 14, 'O', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1095, 4, 'AVAILABILITY', 'Avail. (days)', 15, 'P', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1096, 4, 'SUPPLIER_NOTES', 'Supplier Notes', 16, 'Q', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1097, 4, 'PRECIO_VSS', 'PRECIO VSS', 17, 'R', NULL, false, NULL, '2026-01-25 21:33:57.805934', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (887, 5, 'PRECIO_VSS', 'PRECIO VSS', 20, 'U', NULL, false, NULL, '2026-01-24 22:39:31.132634', '#FFFF00', '#000000', false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (971, 7, 'PRECIO_VSS', 'PRECIO VSS', 21, 'V', NULL, false, NULL, '2026-01-24 23:01:11.987739', '#FFFF00', '#000000', false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (976, 7, 'TOTAL', 'Total Price', 15, 'P', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (977, 7, 'SDOC', 'sDoC', 17, 'R', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (978, 7, 'QUANTITY', 'Quantity', 10, 'K', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (979, 7, 'VAT', 'VAT %', 14, 'O', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (980, 7, 'UNIT_PRICE', 'Unit Price ( USD )', 11, 'L', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (981, 7, 'ITEM_CODE', 'Part Number', 4, 'E', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (982, 7, 'CONTRACT_PRICE', 'Contract Price', 9, 'J', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (983, 7, 'VENDOR_REMARKS', 'Vendor Remarks', 18, 'S', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (984, 7, 'PRODUCT_CODE', 'Product Code', 2, 'C', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (985, 7, 'ITEM_NAME', 'Description', 3, 'D', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (986, 7, 'BRAND', 'Brand', 5, 'F', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (987, 7, 'DISCOUNT', 'Discount %', 13, 'N', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (988, 7, 'UOM', 'Unit', 7, 'H', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (989, 7, 'OFFICE_REMARKS', 'Office Remarks', 20, 'U', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (990, 7, 'PACKAGE', 'Package', 8, 'I', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (991, 7, 'MD', 'MD', 16, 'Q', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (992, 7, 'LINE_NO', 'No', 0, 'A', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (993, 7, 'WEIGHT', 'Weight', 6, 'G', NULL, false, NULL, '2026-01-24 23:43:02.938648', '#9DBEC3', '#1F497D', true, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1009, 2, 'TOTAL', 'TOTAL', 10, 'K', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1010, 2, 'UOM', 'UNIT OF MEASURE', 5, 'F', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1011, 2, 'DESCRIPTION', 'ITEM DESCRIPTION', 4, 'E', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1012, 2, 'QUANTITY', 'QUANTITY ORDER', 6, 'G', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1013, 2, 'CATEGORY', 'FOOD CATEGORIES', 2, 'C', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1014, 2, 'UNIT_PRICE', 'PRICE', 7, 'H', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1015, 2, 'ITEM_CODE', 'MCTC ''S REF NO', 1, 'B', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1016, 2, 'SUPPLIER_COMMENTS', 'SUPPLIER COMMENTS', 8, 'I', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1017, 2, 'ITEM_NAME', 'ITEM', 3, 'D', NULL, false, NULL, '2026-01-24 23:43:03.136574', '#D9E1F2', '#000000', true, false, true);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1074, 3, 'PRECIO_VSS', 'Precio VSS', 20, 'U', NULL, false, NULL, '2026-01-25 21:06:50.552379', '#FFE0B2', NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (973, 1, 'PRECIO_VSS', 'PRECIO VSS', 19, 'T', NULL, false, NULL, '2026-01-24 23:03:08.819881', '#FFFF00', '#000000', false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1077, 1, 'SUPPLIER_COMMENTS', 'Supplier Comments', 15, 'P', NULL, false, NULL, '2026-01-25 21:32:55.130461', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1078, 1, 'COMMENTS', 'Comments', 16, 'Q', NULL, false, NULL, '2026-01-25 21:32:55.130461', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1079, 1, 'TOTAL', 'Total Cost', 17, 'R', NULL, false, NULL, '2026-01-25 21:32:55.130461', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1080, 1, 'UNKNOWN', '0', 18, 'S', NULL, false, NULL, '2026-01-25 21:32:55.130461', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (974, 2, 'PRECIO_VSS', 'PRECIO VSS', 11, 'L', NULL, false, NULL, '2026-01-24 23:03:08.819881', '#FFFF00', '#000000', false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (994, 1, 'QUANTITY', 'Requested Quantity', 5, 'F', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (995, 1, 'METRIC', 'Metric', 12, 'M', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (996, 1, 'UNIT_PRICE', 'Unit Cost', 14, 'O', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (997, 1, 'CASE_SIZE', 'Case Size', 9, 'J', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (998, 1, 'EXPIRY_DATE', 'Expiry Date', 4, 'E', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (999, 1, 'ITEM_NAME', 'Item - Description', 1, 'B', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1000, 1, 'CASE', 'Case', 8, 'I', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1001, 1, 'BRAND', 'Brand', 13, 'N', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1002, 1, 'UOM', 'OCL Uom', 6, 'G', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1003, 1, 'CATEGORY', 'Category', 0, 'A', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1004, 1, 'PACKAGE', 'Package', 10, 'K', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1005, 1, 'PACKAGE_SIZE', 'Package Size', 11, 'L', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1006, 1, 'OCL_CODE', 'OCL Code', 2, 'C', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1007, 1, 'SUPPLIER_CODE', 'Supplier Code', 7, 'H', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1008, 1, 'VSC_CODE', 'VSC Code', 3, 'D', NULL, false, NULL, '2026-01-24 23:43:03.078442', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1044, 5, 'TOTAL', 'Total Amount', 16, 'Q', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1045, 5, 'VESSEL', 'Vessel', 2, 'C', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1046, 5, 'QUALITY', 'Quality', 8, 'I', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1047, 5, 'QUANTITY', 'Quantity', 10, 'K', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1048, 5, 'UNIT_PRICE', 'Unit Price', 12, 'M', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1049, 5, 'ITEM_CODE', 'Part#', 1, 'B', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1050, 5, 'DELIVERY_DAYS', 'Del. Days', 14, 'O', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1051, 5, 'ITEM_NAME', 'Description', 3, 'D', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1052, 5, 'DISCOUNT', 'Disc.%', 13, 'N', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1053, 5, 'NOTES', 'Notes', 18, 'S', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1054, 5, 'UOM', 'Unit', 9, 'J', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1055, 5, 'PACKAGE_SIZE', 'Package Size', 17, 'R', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1056, 5, 'IMPA_ISSA', 'IMPA/ISSA#', 19, 'T', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1057, 5, 'LINE_NO', 'No.', 0, 'A', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);
INSERT INTO public.formato_columnas (columna_id, formato_id, campo_estandar, nombre_columna_original, indice_columna, letra_columna, tipo_dato, requerido, descripcion, fecha_creacion, color_fondo, color_texto, es_negrita, es_cursiva, tiene_borde) VALUES (1058, 5, 'SELLER_NO', 'Seller #', 15, 'P', NULL, false, NULL, '2026-01-24 23:43:03.432201', NULL, NULL, false, false, false);


--
-- Name: broker_formatos_formato_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.broker_formatos_formato_id_seq', 35, true);


--
-- Name: broker_metadata_metadata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.broker_metadata_metadata_id_seq', 447, true);


--
-- Name: brokers_broker_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.brokers_broker_id_seq', 39, true);


--
-- Name: formato_columnas_columna_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formato_columnas_columna_id_seq', 1097, true);


--
-- PostgreSQL database dump complete
--

\unrestrict HnfqlStKn8i6X8WVAekbugQdArXEKHsoZjTtd0qShQNEdomBiVYdujCLkVgVG1S

